### PR TITLE
Byzpaxos

### PR DESCRIPTION
**Pull request by muenchnerkindl**
Added Byzantine Paxos spec and proofs to examples directory.

### CODE REVIEW

**Comment by damiendoligez** [comment]
@muenchnerkindl Weren't you supposed to also remove the file from the test suite?

**Comment by muenchnerkindl** [comment]
Removed the directory from the regression suite.

**Comment by muenchnerkindl** [comment]
I will again ignore the failed tests because they are not related to the PR.

**Review by damiendoligez — APPROVED** [review]
LGTM

**Comment by lemmy** [comment]
The build breakage is bogus anyway because [pr.yml](https://github.com/tlaplus/tlapm/blob/b4697ade6d5fdcd78e078d660c57254517ca6ba5/.github/workflows/pr.yml#L12) is set to run with OCaml `4.08.1` but this PR still uses the old `4.06.1`.  I expect this to be resolved after this merge.

**Pull request merged**
